### ISSUE TITLE
Where dit i go wrong with config. 

### ISSUE THREAD

**Issue by edegraaff** [Limych/ha-snowtire#129]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I am trying to get the snowtire function active for the Netherlands in my self hosted Home Assistant docker on my nas.
HA is working, all other integrations are ok and working. 
I read over and over your documentation but i fail to get the sensor working 
Entity gives option "not avalible" error in the config section.

### Describe the solution you'd like

Could you add some extra lines in the documentation? 
Some assumptions: The sensor is aware of the location of the HA service (as is my location)
The location is serviced by the wether service > i checked it and it is able to find Leiden (nearby)
I used your example in my sensor config 
# Example configuration.yaml entry
binary_sensor:
  - platform: snowtire
    weather: weather.gismeteo_daily
    unique_id: 1234567

HA Core 2023.11.3
HA Frontend 20231030.2

### Describe alternatives you've considered

Checked docu, checked if the webservices weather.gismeteo_daily is existing

### Additional context

2023-12-03 18:01:34.536 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2023-12-03 18:01:34.563 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.snowtire fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/snowtire/binary_sensor.py", line 160, in async_update
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Unable to find an entity called weather.gismeteo_daily

**Comment by Limych** [comment]
> Unable to find an entity called weather.gismeteo_daily

To use the sensor, you need to have a weather entity from any weather forecast provider convenient for you. Judging by the line from the logs quoted above, you simply copied the example from the documentation without substituting the correct weather entity. Either substitute the correct value or create a weather entity from the GisMeteo provider.

There is nothing to edit in the documentation - it is written there initially.
