### ISSUE TITLE
HA 2024.1.0 deprecations

### ISSUE THREAD

**Issue by tjorim** [Limych/ha-snowtire#139]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Updated to HA version 2024.1.0b0 and saw the following warning.

### Describe the solution you'd like

Fix the deprecation.

### Describe alternatives you've considered

n/a

### Additional context

```
2023-12-28 19:23:24.294 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from snowtire, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/Limych/ha-snowtire/issues
```

PS: there is only this template for feature requests, not for a bug report.

**Comment by Limych** [comment]
Fixed in #150
