### ISSUE TITLE
Polish translation not available in version 1.2.0 (missing file).

### ISSUE THREAD

**Issue by nepozs** [Limych/ha-snowtire#20]
**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment]
Thank you. There was a very strange situation...

**Comment by nepozs** [comment]
It is working properly now.
