### ISSUE TITLE
Add German Translation

### ISSUE THREAD

**Issue by LuckyTriple7** [Limych/ha-snowtire#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

German Translation
binary_sensor.de.json

**Describe alternatives you've considered**

```
{
  "state": {
    "snowtire__type": {
      "off": "Sommer",
      "on": "Winter"
    }
  }
}
```

**Additional context**

**Comment by Limych** [comment]
Please, open pull request with this translation.
