### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by Dutchy-79** [Limych/ha-snowtire#34]
**Is your feature request related to a problem? Please describe.**

Add Dutch translation

**Describe the solution you'd like**

I'd like to contribute the dutch translation
**Describe alternatives you've considered**

Just adding Dutch translaion
**Additional context**

Working my way through the template to add Dutch translation
Option 1:
{
  "state": {
    "snowtire__type": {
      "off": "Zomerbanden",
      "on": "Winterbanden"
    }
  }
}

Option 2: might be best due length
{
  "state": {
    "snowtire__type": {
      "off": "Zomer",
      "on": "Winter"
    }
  }
}

file name should be binary_sensor.nl.json

Also the file binary_sensor.uk.json is wrong because that's UA not UK
https://www.iso.org/obp/ui/#iso:code:3166:UA

**Comment by Limych** [comment]
For adding Dutch translation, please, open pull request. The shortest by length texts is preferred.

Language tag for Ukrainian translation is correct.

See [HA documentation](https://developers.home-assistant.io/docs/translations/#maintainer-steps-to-add-a-new-language):
> Language tags have to follow BCP 47. A list of most language tags can be found here: [IANA subtag registry](http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)
