### ISSUE TITLE
Not available in HACS

### ISSUE THREAD

**Issue by denysdovhan** [Limych/ha-snowtire#4]
I've tried to use the installation guide and noticed that this integration is not searchable in HACS repo. Please, consider adding your repo there 🙏🏻

**Comment by Limych** [comment]
Sorry, this component is in alpha version only.  If you want to test it, you have to install it manually.

**Comment by Limych** [comment]
I changed my mind. Yes, perhaps now is the time to publish the sensor on HACS. But it will be done under a new name: Snowtire

**Comment by Limych** [comment]
https://github.com/hacs/default/pull/849
